export const GET_TESTS = 'GET_TESTS';
export const GET_TESTS_SUCCESS = 'GET_TESTS_SUCCESS';
export const GET_TEST = 'GET_TEST';
export const GET_TEST_SUCCESS = 'GET_TEST_SUCCESS';
export const GET_TEST_FAILURE = 'GET_TEST_FAILURE';
export const SET_FEEDBACK = 'SET_FEEDBACK';
export const GET_FEEDBACK_SUCCESS = 'GET_FEEDBACK_SUCCESS';
export const GET_FEEDBACK_FAILURE = 'GET_FEEDBACK_FAILURE';
